version: 2
jobs:
  build:
    docker:
      image: circleci/node:8.9.4
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-yarn-{{ arch }}-{{ checksum "yarn.lock" }}
            - v1-yarn-{{ arch }}
      - run:
        name: Install dependencies
        command: yarn install
      - save_cache:
          key: v1-yarn-{{ arch }}-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
        name: Build
        command: yarn build
      - run:
        name: Lint
        command: yarn lint
      - run:
        name: Test
        command: yarn test
